[package]
name = "ken-matsui/base64"
version = "0.1.2"
description = "Base64 in WebAssembly"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ken-matsui/base64-cli"
homepage = "https://github.com/ken-matsui/base64-cli#readme"

[[module]]
name = "base64"
source = "target/wasm32-wasi/release/base64-cli.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "base64"
module = "base64"
